[package]
name = "futsu_no_linux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# [[bin]]
# name = "cat"
# path = "src/cat.rs"
